### ISSUE TITLE
complex yaml

### ISSUE THREAD

**Issue by jongacnik** [enokidotsite/enoki#6]
Right now only simple yaml arrays are recognized, ideally we can get this working with more complex yaml structures as well. Examples:

```yaml
----

field:
  key:
    subfield: value

----

field:
  key:
    - value
    - value
    - value

----
```
